// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.dromara.hmily.demo.tars.inventory.servant.inventoryapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface InventoryServant {

	 boolean decrease(@TarsMethodParameter(name="productId")String productId, @TarsMethodParameter(name="count")int count);
}
