// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.dromara.hmily.demo.tars.order.servant.inventoryapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;
import java.util.concurrent.CompletableFuture;

@Servant
public interface InventoryPrx {

	 boolean decrease(@TarsMethodParameter(name="productId")String productId, @TarsMethodParameter(name="count")int count);

	 boolean decrease(@TarsMethodParameter(name="productId")String productId, @TarsMethodParameter(name="count")int count, @TarsContext java.util.Map<String, String> ctx);

	 void async_decrease(@TarsCallback InventoryPrxCallback callback, @TarsMethodParameter(name="productId")String productId, @TarsMethodParameter(name="count")int count);

	 void async_decrease(@TarsCallback InventoryPrxCallback callback, @TarsMethodParameter(name="productId")String productId, @TarsMethodParameter(name="count")int count, @TarsContext java.util.Map<String, String> ctx);

	 CompletableFuture<java.lang.Boolean>  promise_decrease(@TarsMethodParameter(name="productId")String productId, @TarsMethodParameter(name="count")int count);

	 CompletableFuture<java.lang.Boolean>  promise_decrease(@TarsMethodParameter(name="productId")String productId, @TarsMethodParameter(name="count")int count, @TarsContext java.util.Map<String, String> ctx);
}
