// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.dromara.hmily.demo.tars.order.servant.inventoryapp;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class InventoryPrxCallback extends TarsAbstractCallback {

	public abstract void callback_decrease(boolean ret);

}
