server:
   port: 8888
   context-path: /tcc-admin

spring:
   application:
      name: tcc-admin
   profiles:
     active: db

tcc:
  admin :
    userName : admin
    password : admin

compensation:
   application:
      list : account-service,inventory-service,order-service
   serializer :
      support: kryo
   retry :
      max: 10