// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory_service.proto

package org.dromara.hmily.demo.grpc.inventory.service;

public interface InventoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InventoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool result = 1;</code>
   */
  boolean getResult();

  /**
   * <code>optional string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
