// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory_service.proto

package org.dromara.hmily.demo.grpc.inventory.service;

public interface InventoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InventoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string productId = 1;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>optional string productId = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>optional int32 count = 2;</code>
   */
  int getCount();
}
