server:
    port: 8884
    address: 0.0.0.0
    servlet:
        context-path: /


spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.01:3306/hmily_stock?useUnicode=true&characterEncoding=utf8
        username: root
        password:
    application:
        name: sofa-inventory
com:
    alipay:
        sofa:
            rpc:
                registry-address: zookeeper://127.0.0.1:2181

mybatis:
    type-aliases-package: org.dromara.hmily.demo.common.inventory.entity
    config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: debug
        org.dromara.hmily.demo.bonuspoint: debug
        org.dromara.hmily.demo.lottery: debug
        org.dromara.hmily.demo: debug
        com.alipay.test: INFO
        io.netty: info
    path: "./logs"
