server:
  port: 8883
  address: 0.0.0.0
  servlet:
    context-path: /inventory-service

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.98:3306/tcc_stock?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
    application:
      name: inventory-service

mybatis:
  type-aliases-package: com.hmily.tcc.demo.springcloud.inventory.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
 instance:
   prefer-ip-address: true

inventory-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.hmily.tcc.bonuspoint: debug
        com.hmily.tcc.lottery: debug
        com.hmily.tcc: debug
        io.netty: info
    path: "./logs"


