// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory_service.proto

package org.dromara.hmily.demo.grpc.inventory.service;

public final class InventoryServiceProto {
  private InventoryServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InventoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InventoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InventoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InventoryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027inventory_service.proto\"4\n\020InventoryRe" +
      "quest\022\021\n\tproductId\030\001 \001(\t\022\r\n\005count\030\002 \001(\005\"" +
      "4\n\021InventoryResponse\022\016\n\006result\030\001 \001(\010\022\017\n\007" +
      "content\030\002 \001(\t2E\n\020InventoryService\0221\n\010dec" +
      "rease\022\021.InventoryRequest\032\022.InventoryResp" +
      "onseBN\n-org.dromara.hmily.demo.grpc.inve" +
      "ntory.serviceB\025InventoryServiceProtoP\001\242\002" +
      "\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InventoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InventoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InventoryRequest_descriptor,
        new java.lang.String[] { "ProductId", "Count", });
    internal_static_InventoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_InventoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InventoryResponse_descriptor,
        new java.lang.String[] { "Result", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
