server:
  port: 8089
  servlet:
    context-path: /
  address: 0.0.0.0
spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/hmily_order?useUnicode=true&characterEncoding=utf8
        username: root
        password:
    application:
      name: sofa-order
com:
  alipay:
    sofa:
      rpc:
        registry-address: zookeeper://127.0.0.1:2181
        bolt-port: 8890

mybatis:
  type-aliases-package: org.dromara.hmily.demo.common.order.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: debug
        org.dromara.hmily.demo.bonuspoint: debug
        org.dromara.hmily.demo.lottery: debug
        org.dromara.hmily.demo: debug
        com.alipay.test: INFO
    path: "./logs"


