// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_service.proto

package org.dromara.hmily.demo.grpc.account.service;

public interface AccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool result = 1;</code>
   */
  boolean getResult();
}
