server:
  port: 8084
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.98:3306/tcc_stock?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456


mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.inventory.api.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.hmily.tcc.bonuspoint: info
        com.hmily.tcc.lottery: info
        com.hmily.tcc: info
        io.netty: info
    path: "./logs"

