server:
  port: 8084
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://10.4.4.202:3306/tcc_stock?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123123


mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.inventory.api.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.hmily.bonuspoint: info
        com.hmily.lottery: debug
        com.hmily: debug
        io.netty: info

    path: "./logs"

