// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.dromara.hmily.demo.tars.order.servant.accountapp;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class AccountPrxCallback extends TarsAbstractCallback {

	public abstract void callback_payment();

}
