// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_service.proto

package org.dromara.hmily.demo.grpc.account.service;

public final class AccountServiceProto {
  private AccountServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025account_service.proto\"0\n\016AccountReques" +
      "t\022\016\n\006userId\030\001 \001(\t\022\016\n\006amount\030\002 \001(\t\"!\n\017Acc" +
      "ountResponse\022\016\n\006result\030\001 \001(\0102>\n\016AccountS" +
      "ervice\022,\n\007payment\022\017.AccountRequest\032\020.Acc" +
      "ountResponseBJ\n+org.dromara.hmily.demo.g" +
      "rpc.account.serviceB\023AccountServiceProto" +
      "P\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountRequest_descriptor,
        new java.lang.String[] { "UserId", "Amount", });
    internal_static_AccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
