// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_service.proto

package org.dromara.hmily.demo.grpc.account.service;

public interface AccountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>optional string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>optional string amount = 2;</code>
   */
  java.lang.String getAmount();
  /**
   * <code>optional string amount = 2;</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();
}
